version: '3.8'

services:
  servidor-web:
    image: nginx:alpine
    container_name: meu-site-nginx
    ports:
      - "8081:80" # A porta 8080 é a que acessamos no navegador
    restart: always

    #git checkout -b Terra-52
    #git add .
    #git commit -m "add alterações Terra 52"
    #git push --set-upstream origin Terra-52